name: Deploy Infrastructure

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: "eu-north-1"
  TF_VERSION: "1.5.0"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=terraform init
        env:
          TF_VAR_github_token: ${{ secrets.ORG_TOKEN }}

      - name: Terraform Plan
        run: |
          terraform -chdir=terraform plan
        env:
          TF_VAR_github_token: ${{ secrets.ORG_TOKEN }}
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_customer_name: new-monorepo
          TF_VAR_github_org_name: cratfapp
          TF_VAR_github_repo_name: backend
          TF_VAR_github_branch: main

      - name: Terraform Apply
        run: |
          terraform -chdir=terraform apply -auto-approve
        env:
          TF_VAR_github_token: ${{ secrets.ORG_TOKEN }}
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_customer_name: new-monorepo
          TF_VAR_github_org_name: cratfapp
          TF_VAR_github_repo_name: backend
          TF_VAR_github_branch: main
